use bonhomme_core::{
    RenderedFile, SemanticGraph, Slice, SymbolNode, metadata_bool, metadata_string,
};
use uuid::Uuid;

pub fn render_files(graph: &SemanticGraph) -> Vec<RenderedFile> {
    let mut files = graph
        .root_symbols()
        .into_iter()
        .filter(|symbol| symbol.kind == "file")
        .map(|file_symbol| render_file(graph, file_symbol))
        .collect::<Vec<_>>();

    files.sort_by(|a, b| a.path.cmp(&b.path));
    files
}

pub fn render_slice(
    graph: &SemanticGraph,
    base_revision: String,
    root_symbols: Vec<Uuid>,
) -> Slice {
    let requested = root_symbols
        .iter()
        .filter_map(|symbol_id| graph.symbols.get(symbol_id))
        .collect::<Vec<_>>();

    let files = if requested.is_empty() {
        render_files(graph)
    } else {
        let mut files = Vec::new();
        for symbol in requested {
            let file_symbol = nearest_file_symbol(graph, symbol).unwrap_or(symbol);
            files.push(render_file(graph, file_symbol));
        }
        files.sort_by(|a, b| a.path.cmp(&b.path));
        files.dedup_by(|a, b| a.path == b.path);
        files
    };

    Slice {
        id: Uuid::new_v4(),
        base_revision,
        root_symbols,
        files,
    }
}

fn nearest_file_symbol<'a>(
    graph: &'a SemanticGraph,
    symbol: &'a SymbolNode,
) -> Option<&'a SymbolNode> {
    if symbol.kind == "file" {
        return Some(symbol);
    }

    let mut current = symbol;
    while let Some(parent_id) = current.parent_id {
        current = graph.symbols.get(&parent_id)?;
        if current.kind == "file" {
            return Some(current);
        }
    }
    None
}

fn render_file(graph: &SemanticGraph, file_symbol: &SymbolNode) -> RenderedFile {
    let path =
        metadata_string(&file_symbol.metadata, "path").unwrap_or_else(|| file_symbol.name.clone());
    let mut content = String::new();
    let preamble = metadata_string(&file_symbol.metadata, "preamble").unwrap_or_default();
    let (shebang, preamble) = split_shebang(&preamble);
    if let Some(shebang) = shebang {
        content.push_str(shebang);
        content.push('\n');
    }
    content.push_str(
        "// Generated by bonhomme. Edit through slices; operation replay is authoritative.\n",
    );
    content.push('\n');
    if !preamble.trim().is_empty() {
        content.push_str(preamble.trim());
        content.push_str("\n\n");
    }

    for child in graph.children_of(file_symbol.id) {
        render_symbol(graph, child, 0, &mut content);
        content.push('\n');
    }

    RenderedFile { path, content }
}

fn split_shebang(preamble: &str) -> (Option<&str>, &str) {
    let Some(rest) = preamble.strip_prefix("#!") else {
        return (None, preamble);
    };
    match rest.find('\n') {
        Some(index) => {
            let end = "#!".len() + index;
            (Some(&preamble[..end]), &preamble[end + 1..])
        }
        None => (Some(preamble), ""),
    }
}

fn render_symbol(graph: &SemanticGraph, symbol: &SymbolNode, indent: usize, out: &mut String) {
    match symbol.kind.as_str() {
        "class" => render_class(graph, symbol, indent, out),
        "method" | "static-method" | "getter" | "static-getter" | "setter" | "static-setter" => {
            render_method(symbol, indent, out)
        }
        "function" => render_function(symbol, indent, out),
        "property" => render_property(symbol, indent, out),
        _ => {
            write_indent(indent, out);
            out.push_str(&format!(
                "/* unrendered {} symbol named {} */\n",
                symbol.kind, symbol.name
            ));
        }
    }
}

fn render_class(graph: &SemanticGraph, symbol: &SymbolNode, indent: usize, out: &mut String) {
    render_doc(symbol, indent, out);
    write_indent(indent, out);
    if let Some(declaration) = metadata_string(&symbol.metadata, "declaration") {
        out.push_str(&declaration);
        out.push_str(" {\n");
    } else {
        if metadata_bool(&symbol.metadata, "exported") {
            out.push_str("export ");
        }
        out.push_str(&format!("class {}", symbol.name));
        out.push_str(" {\n");
    }

    let children = graph.children_of(symbol.id);
    if children.is_empty() {
        write_indent(indent + 2, out);
        out.push_str("// empty\n");
    } else {
        for child in children {
            render_symbol(graph, child, indent + 2, out);
        }
    }

    write_indent(indent, out);
    out.push_str("}\n");
}

fn render_method(symbol: &SymbolNode, indent: usize, out: &mut String) {
    let signature = metadata_string(&symbol.metadata, "signature")
        .unwrap_or_else(|| format!("{}(): void", symbol.name));
    render_doc(symbol, indent, out);
    write_indent(indent, out);
    out.push_str(&signature);
    out.push_str(" {\n");
    render_body(symbol.body.as_deref().unwrap_or(""), indent + 2, out);
    write_indent(indent, out);
    out.push_str("}\n");
}

fn render_function(symbol: &SymbolNode, indent: usize, out: &mut String) {
    let signature = metadata_string(&symbol.metadata, "signature")
        .unwrap_or_else(|| format!("{}(): void", symbol.name));
    render_doc(symbol, indent, out);
    write_indent(indent, out);
    if let Some(declaration) = metadata_string(&symbol.metadata, "declaration") {
        out.push_str(&declaration);
    } else {
        if metadata_bool(&symbol.metadata, "exported") {
            out.push_str("export ");
        }
        out.push_str(&format!("function {}", signature));
    }
    out.push_str(" {\n");
    render_body(symbol.body.as_deref().unwrap_or(""), indent + 2, out);
    write_indent(indent, out);
    out.push_str("}\n");
}

fn render_property(symbol: &SymbolNode, indent: usize, out: &mut String) {
    let declaration = metadata_string(&symbol.metadata, "declaration")
        .unwrap_or_else(|| format!("{}: unknown;", symbol.name));
    render_doc(symbol, indent, out);
    write_indent(indent, out);
    out.push_str(&declaration);
    out.push('\n');
}

/// Render a symbol's leading `/** … */` doc (stored as `doc` metadata) above its declaration,
/// re-indented to the symbol's column so nested members read cleanly.
fn render_doc(symbol: &SymbolNode, indent: usize, out: &mut String) {
    let Some(doc) = metadata_string(&symbol.metadata, "doc") else {
        return;
    };
    for (index, line) in doc.lines().enumerate() {
        write_indent(indent, out);
        if index == 0 {
            out.push_str(line.trim_start()); // "/**"
        } else {
            // Continuation lines (` * …`, ` */`) align their `*` under the opening `/**`.
            out.push(' ');
            out.push_str(line.trim_start());
        }
        out.push('\n');
    }
}

fn render_body(body: &str, indent: usize, out: &mut String) {
    if body.trim().is_empty() {
        write_indent(indent, out);
        out.push_str("// no-op\n");
        return;
    }

    for line in body.lines() {
        write_indent(indent, out);
        out.push_str(line.trim_end());
        out.push('\n');
    }
}

fn write_indent(indent: usize, out: &mut String) {
    for _ in 0..indent {
        out.push(' ');
    }
}
