//! The formatter boundary. bonhomme renders a *canonical* projection of the semantic graph; when
//! those files land in a repo that has its own formatter, the canonical form would show up as
//! reformatting noise in the Git diff. This module runs a project-configured formatter over rendered
//! content at the write/compare seam, so a touched file matches the repo's style instead.
//!
//! Configured by the `[format]` table, keyed by file extension; the value is an argv-like command
//! that reads file content on stdin and writes the formatted result to stdout (e.g.
//! `rs = "rustfmt"`, `go = "gofmt"`, `ts = "prettier --stdin-filepath {path}"`). A `{path}`
//! placeholder is substituted as an argument value without invoking a shell. Formatting is
//! **best-effort and never loses content**: an unconfigured extension, a binary file, or a failing
//! formatter passes the content through unchanged. It is applied symmetrically — on `land` (what gets
//! written) and on the render side of `check` (what the round-trip gate measures) — so the gate
//! reflects what landing produces.

use std::collections::BTreeMap;
use std::path::Path;
use std::process::Stdio;

use anyhow::{Context, Result, bail};
use bonhomme_core::{RenderedFile, decode_binary};
use tokio::io::AsyncWriteExt;
use tokio::process::Command;
use tokio::time;

const FORMATTER_TIMEOUT: std::time::Duration = std::time::Duration::from_secs(30);

/// The write-back boundary transform for each rendered file: strip bonhomme's own generated banner
/// (so it never lands in the repo or skews the round-trip gate) and run the configured formatter for
/// the file's extension. Binary envelopes pass through untouched; the banner strip runs even with no
/// formatters configured.
pub async fn format_files(
    mut files: Vec<RenderedFile>,
    formatters: &BTreeMap<String, String>,
) -> Vec<RenderedFile> {
    for file in &mut files {
        // Binary content is a base64 envelope — never run a text formatter over it.
        if decode_binary(&file.content).is_some() {
            continue;
        }
        let content = strip_generated_banner(&file.content);
        file.content = match format_one(&content, Path::new(&file.path), formatters).await {
            Some(formatted) => formatted,
            None => content,
        };
    }
    files
}

/// The marker bonhomme's TypeScript render prepends to generated files. The operation log (not a
/// comment) is authoritative, so the banner is removed at the write-back boundary rather than
/// injected into every landed file — where it would also make the round-trip gate never come clean.
const GENERATED_BANNER_MARKER: &str = "// Generated by bonhomme";

fn strip_generated_banner(content: &str) -> String {
    let Some((first_line, rest)) = content.split_once('\n') else {
        return content.to_string();
    };
    if !first_line.starts_with(GENERATED_BANNER_MARKER) {
        return content.to_string();
    }
    // Drop the banner line and a single immediately-following blank line.
    rest.strip_prefix('\n').unwrap_or(rest).to_string()
}

/// Format a single string by `path`'s extension, returning `Some(formatted)` only when a formatter
/// is configured for the extension and runs successfully.
async fn format_one(
    content: &str,
    path: &Path,
    formatters: &BTreeMap<String, String>,
) -> Option<String> {
    let extension = path.extension().and_then(|extension| extension.to_str())?;
    let command = formatter_argv(formatters.get(extension)?, path).ok()?;
    run_formatter(&command, content).await.ok()
}

fn formatter_argv(command: &str, path: &Path) -> Result<Vec<String>> {
    let mut args = split_command(command)?;
    if args.is_empty() {
        bail!("formatter command is empty");
    }
    for arg in &mut args {
        *arg = arg.replace("{path}", &path.to_string_lossy());
    }
    Ok(args)
}

fn split_command(command: &str) -> Result<Vec<String>> {
    let mut args = Vec::new();
    let mut current = String::new();
    let mut quote = None;
    let mut chars = command.chars();

    while let Some(ch) = chars.next() {
        match (quote, ch) {
            (None, ch) if ch.is_whitespace() => {
                if !current.is_empty() {
                    args.push(std::mem::take(&mut current));
                }
            }
            (None, '\'' | '"') => quote = Some(ch),
            (Some(active), ch) if ch == active => quote = None,
            (_, '\\') => {
                if let Some(next) = chars.next() {
                    current.push(next);
                } else {
                    current.push('\\');
                }
            }
            _ => current.push(ch),
        }
    }

    if let Some(active) = quote {
        bail!("unterminated {active} quote in formatter command");
    }
    if !current.is_empty() {
        args.push(current);
    }
    Ok(args)
}

async fn run_formatter(command: &[String], content: &str) -> Result<String> {
    let Some((program, args)) = command.split_first() else {
        bail!("formatter command is empty");
    };
    let mut command_builder = Command::new(program);
    command_builder
        .args(args)
        .kill_on_drop(true)
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::null());
    let mut child = command_builder
        .spawn()
        .with_context(|| format!("spawning formatter `{}`", command.join(" ")))?;

    // Write stdin from a task while we read stdout, so a formatter that streams output cannot
    // deadlock against a full pipe.
    let mut stdin = child.stdin.take().context("formatter stdin unavailable")?;
    let input = content.to_string();
    let writer = tokio::spawn(async move {
        let _ = stdin.write_all(input.as_bytes()).await;
        // stdin is dropped here, signalling EOF to the formatter.
    });
    let output = time::timeout(FORMATTER_TIMEOUT, child.wait_with_output())
        .await
        .context("formatter timed out")??;
    let _ = writer.await;

    if !output.status.success() {
        bail!(
            "formatter `{}` exited with {}",
            command.join(" "),
            output.status
        );
    }
    String::from_utf8(output.stdout).context("formatter produced non-UTF-8 output")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn file(path: &str, content: &str) -> RenderedFile {
        RenderedFile {
            path: path.to_string(),
            content: content.to_string(),
        }
    }

    #[tokio::test]
    async fn formats_configured_extension_and_passes_others_through() {
        // `tr a-z A-Z` is a stand-in formatter: reads stdin, uppercases, writes stdout.
        let mut formatters = BTreeMap::new();
        formatters.insert("up".to_string(), "tr a-z A-Z".to_string());

        let out = format_files(
            vec![file("a.up", "hello"), file("b.txt", "hello")],
            &formatters,
        )
        .await;

        assert_eq!(out[0].content, "HELLO"); // configured extension is formatted
        assert_eq!(out[1].content, "hello"); // unconfigured extension untouched
    }

    #[tokio::test]
    async fn failing_formatter_passes_content_through() {
        let mut formatters = BTreeMap::new();
        formatters.insert("x".to_string(), "exit 1".to_string());

        let out = format_files(vec![file("a.x", "keep me")], &formatters).await;

        assert_eq!(out[0].content, "keep me"); // never lose content on formatter failure
    }

    #[test]
    fn formatter_path_placeholder_is_one_argument() {
        let argv = formatter_argv(
            "prettier --stdin-filepath={path} --flag '{path}'",
            Path::new("src/a file.ts"),
        )
        .unwrap();

        assert_eq!(
            argv,
            vec![
                "prettier",
                "--stdin-filepath=src/a file.ts",
                "--flag",
                "src/a file.ts"
            ]
        );
    }

    #[tokio::test]
    async fn empty_config_is_a_no_op() {
        let out = format_files(vec![file("a.up", "hello")], &BTreeMap::new()).await;
        assert_eq!(out[0].content, "hello");
    }

    #[tokio::test]
    async fn generated_banner_is_stripped_even_without_a_formatter() {
        let banner = "// Generated by bonhomme. Edit through slices; replay is authoritative.";
        let out = format_files(
            vec![file("a.ts", &format!("{banner}\n\nexport const x = 1;\n"))],
            &BTreeMap::new(),
        )
        .await;
        assert_eq!(out[0].content, "export const x = 1;\n");
    }

    #[test]
    fn strip_banner_leaves_ordinary_comments_alone() {
        assert_eq!(
            strip_generated_banner("// a real comment\nx\n"),
            "// a real comment\nx\n"
        );
        assert_eq!(strip_generated_banner("no comment\n"), "no comment\n");
    }
}
