use crate::core::{Operation, SemanticGraph, SymbolNode, metadata_bool, metadata_string};
use anyhow::{Context, Result, bail};
use regex::Regex;
use serde::{Deserialize, Serialize};
use serde_json::json;
use std::{
    collections::{BTreeMap, BTreeSet},
    fs as std_fs,
    path::Path,
};
use tokio::{fs, process::Command, time};
use uuid::Uuid;

use crate::lang::{LanguagePlugin, ValidateFuture};
pub use crate::lang::{RenderedFile, Slice};

/// The TypeScript implementation of [`LanguagePlugin`]. A zero-sized handle that routes the
/// engine's render/import/diff/validate calls to this module's TypeScript-specific functions, so
/// `core` and `storage` never depend on TypeScript directly.
#[derive(Clone, Copy, Debug, Default)]
pub struct TypeScriptPlugin;

impl LanguagePlugin for TypeScriptPlugin {
    fn render(&self, graph: &SemanticGraph) -> Vec<RenderedFile> {
        render_files(graph)
    }

    fn render_slice(
        &self,
        graph: &SemanticGraph,
        base_revision: String,
        root_symbols: Vec<Uuid>,
    ) -> Slice {
        render_slice(graph, base_revision, root_symbols)
    }

    fn import(&self, files: &[RenderedFile]) -> Result<Vec<Operation>> {
        import_typescript_files(files)
    }

    fn diff(&self, original: &[RenderedFile], modified: &[RenderedFile]) -> Result<Vec<Operation>> {
        diff_slice(original, modified)
    }

    fn read_source_tree(&self, root: &Path) -> Result<Vec<RenderedFile>> {
        read_typescript_tree(root)
    }

    fn validate<'a>(&'a self, files: &'a [RenderedFile]) -> ValidateFuture<'a> {
        Box::pin(validate_typescript_files(files))
    }
}

pub fn render_files(graph: &SemanticGraph) -> Vec<RenderedFile> {
    let mut files = graph
        .root_symbols()
        .into_iter()
        .filter(|symbol| symbol.kind == "file")
        .map(|file_symbol| render_file(graph, file_symbol))
        .collect::<Vec<_>>();

    files.sort_by(|a, b| a.path.cmp(&b.path));
    files
}

pub fn render_slice(
    graph: &SemanticGraph,
    base_revision: String,
    root_symbols: Vec<Uuid>,
) -> Slice {
    let requested = root_symbols
        .iter()
        .filter_map(|symbol_id| graph.symbols.get(symbol_id))
        .collect::<Vec<_>>();

    let files = if requested.is_empty() {
        render_files(graph)
    } else {
        let mut files = Vec::new();
        for symbol in requested {
            let file_symbol = nearest_file_symbol(graph, symbol).unwrap_or(symbol);
            files.push(render_file(graph, file_symbol));
        }
        files.sort_by(|a, b| a.path.cmp(&b.path));
        files.dedup_by(|a, b| a.path == b.path);
        files
    };

    Slice {
        id: Uuid::new_v4(),
        base_revision,
        root_symbols,
        files,
    }
}

fn nearest_file_symbol<'a>(
    graph: &'a SemanticGraph,
    symbol: &'a SymbolNode,
) -> Option<&'a SymbolNode> {
    if symbol.kind == "file" {
        return Some(symbol);
    }

    let mut current = symbol;
    while let Some(parent_id) = current.parent_id {
        current = graph.symbols.get(&parent_id)?;
        if current.kind == "file" {
            return Some(current);
        }
    }
    None
}

fn render_file(graph: &SemanticGraph, file_symbol: &SymbolNode) -> RenderedFile {
    let path =
        metadata_string(&file_symbol.metadata, "path").unwrap_or_else(|| file_symbol.name.clone());
    let mut content = String::new();
    content.push_str(
        "// Generated by bonhomme. Edit through slices; operation replay is authoritative.\n",
    );
    content.push_str(&format!("// bonhomme:file={}\n\n", file_symbol.id));
    if let Some(preamble) = metadata_string(&file_symbol.metadata, "preamble")
        && !preamble.trim().is_empty()
    {
        content.push_str(preamble.trim());
        content.push_str("\n\n");
    }

    for child in graph.children_of(file_symbol.id) {
        render_symbol(graph, child, 0, &mut content);
        content.push('\n');
    }

    RenderedFile { path, content }
}

fn render_symbol(graph: &SemanticGraph, symbol: &SymbolNode, indent: usize, out: &mut String) {
    match symbol.kind.as_str() {
        "class" => render_class(graph, symbol, indent, out),
        "method" => render_method(symbol, indent, out),
        "function" => render_function(symbol, indent, out),
        "property" => render_property(symbol, indent, out),
        _ => {
            write_indent(indent, out);
            out.push_str(&format!(
                "/* bonhomme:unrendered-kind={} symbol={} name={} */\n",
                symbol.kind, symbol.id, symbol.name
            ));
        }
    }
}

fn render_class(graph: &SemanticGraph, symbol: &SymbolNode, indent: usize, out: &mut String) {
    write_indent(indent, out);
    if let Some(declaration) = metadata_string(&symbol.metadata, "declaration") {
        out.push_str(&declaration);
        out.push_str(&format!(" /* bonhomme:symbol={} */ {{\n", symbol.id));
    } else {
        if metadata_bool(&symbol.metadata, "exported") {
            out.push_str("export ");
        }
        out.push_str(&format!(
            "class {} /* bonhomme:symbol={} */ {{\n",
            symbol.name, symbol.id
        ));
    }

    let children = graph.children_of(symbol.id);
    if children.is_empty() {
        write_indent(indent + 2, out);
        out.push_str("// empty\n");
    } else {
        for child in children {
            render_symbol(graph, child, indent + 2, out);
        }
    }

    write_indent(indent, out);
    out.push_str("}\n");
}

fn render_method(symbol: &SymbolNode, indent: usize, out: &mut String) {
    let signature = metadata_string(&symbol.metadata, "signature")
        .unwrap_or_else(|| format!("{}(): void", symbol.name));
    write_indent(indent, out);
    out.push_str(&format!(
        "{} /* bonhomme:symbol={} */ {{\n",
        signature, symbol.id
    ));
    render_body(symbol.body.as_deref().unwrap_or(""), indent + 2, out);
    write_indent(indent, out);
    out.push_str("}\n");
}

fn render_function(symbol: &SymbolNode, indent: usize, out: &mut String) {
    let signature = metadata_string(&symbol.metadata, "signature")
        .unwrap_or_else(|| format!("{}(): void", symbol.name));
    write_indent(indent, out);
    if let Some(declaration) = metadata_string(&symbol.metadata, "declaration") {
        out.push_str(&format!(
            "{} /* bonhomme:symbol={} */ {{\n",
            declaration, symbol.id
        ));
    } else {
        if metadata_bool(&symbol.metadata, "exported") {
            out.push_str("export ");
        }
        out.push_str(&format!(
            "function {} /* bonhomme:symbol={} */ {{\n",
            signature, symbol.id
        ));
    }
    render_body(symbol.body.as_deref().unwrap_or(""), indent + 2, out);
    write_indent(indent, out);
    out.push_str("}\n");
}

fn render_property(symbol: &SymbolNode, indent: usize, out: &mut String) {
    let declaration = metadata_string(&symbol.metadata, "declaration")
        .unwrap_or_else(|| format!("{}: unknown;", symbol.name));
    write_indent(indent, out);
    out.push_str(&declaration);
    out.push_str(&format!(" /* bonhomme:symbol={} */\n", symbol.id));
}

fn render_body(body: &str, indent: usize, out: &mut String) {
    if body.trim().is_empty() {
        write_indent(indent, out);
        out.push_str("// no-op\n");
        return;
    }

    for line in body.lines() {
        write_indent(indent, out);
        out.push_str(line.trim_end());
        out.push('\n');
    }
}

fn write_indent(indent: usize, out: &mut String) {
    for _ in 0..indent {
        out.push(' ');
    }
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ParsedMethod {
    pub symbol_id: Option<Uuid>,
    pub parent_class_id: Option<Uuid>,
    pub name: String,
    pub signature: String,
    pub body: String,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ParsedClass {
    pub symbol_id: Option<Uuid>,
    pub name: String,
    pub methods: Vec<ParsedMethod>,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ParsedFunction {
    pub symbol_id: Option<Uuid>,
    pub name: String,
    pub signature: String,
    pub body: String,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ParsedFile {
    pub path: String,
    pub file_symbol_id: Option<Uuid>,
    pub classes: Vec<ParsedClass>,
    pub functions: Vec<ParsedFunction>,
}

#[derive(Clone, Debug)]
struct ImportedSymbol {
    id: Uuid,
    parent_id: Option<Uuid>,
    body: Option<String>,
}

#[derive(Clone, Debug)]
struct ParsedTopLevel {
    start: usize,
    operations: Vec<Operation>,
}

/// Accumulators threaded through the importer: the symbols seen so far (for reference scanning),
/// a name -> ids index for free-function call resolution, and a (class, name) -> id index for
/// `this.`-qualified call resolution.
#[derive(Default)]
struct ImportIndexes {
    symbols: Vec<ImportedSymbol>,
    name_index: BTreeMap<String, Vec<Uuid>>,
    sibling_index: BTreeMap<(Uuid, String), Uuid>,
}

pub fn read_typescript_tree(root: &Path) -> Result<Vec<RenderedFile>> {
    let mut files = Vec::new();
    let base = if root.is_file() {
        root.parent().unwrap_or_else(|| Path::new("."))
    } else {
        root
    };
    collect_typescript_files(root, base, &mut files)?;
    files.sort_by(|a, b| a.path.cmp(&b.path));
    Ok(files)
}

fn collect_typescript_files(path: &Path, base: &Path, files: &mut Vec<RenderedFile>) -> Result<()> {
    if path.is_dir() {
        let Some(name) = path.file_name().and_then(|name| name.to_str()) else {
            return Ok(());
        };
        if matches!(name, "node_modules" | "dist" | "target" | ".git") {
            return Ok(());
        }
        for entry in std_fs::read_dir(path)? {
            collect_typescript_files(&entry?.path(), base, files)?;
        }
        return Ok(());
    }

    if path.extension().and_then(|extension| extension.to_str()) != Some("ts") {
        return Ok(());
    }
    if path
        .file_name()
        .and_then(|name| name.to_str())
        .is_some_and(|name| name.ends_with(".d.ts"))
    {
        return Ok(());
    }

    let relative_path = path
        .strip_prefix(base)
        .unwrap_or(path)
        .components()
        .map(|component| component.as_os_str().to_string_lossy())
        .collect::<Vec<_>>()
        .join("/");
    files.push(RenderedFile {
        path: relative_path,
        content: std_fs::read_to_string(path)?,
    });
    Ok(())
}

pub fn import_typescript_files(files: &[RenderedFile]) -> Result<Vec<Operation>> {
    let class_re = Regex::new(
        r"(?m)(?P<export>export\s+)?(?:abstract\s+)?\bclass\s+(?P<name>[A-Za-z_$][A-Za-z0-9_$]*)",
    )?;
    let function_re = Regex::new(
        r"(?m)^\s*(?P<export>export\s+)?(?:async\s+)?function\s+(?P<name>[A-Za-z_$][A-Za-z0-9_$]*)\s*\((?:[^()]|\([^()]*\))*\)\s*(?::\s*[^/{]+)?\s*\{",
    )?;
    let method_re = Regex::new(
        r"(?m)^\s*(?:(?:public|private|protected|async|static|readonly|override)\s+)*(?P<name>[A-Za-z_$][A-Za-z0-9_$]*)\s*\((?:[^()]|\([^()]*\))*\)\s*(?::\s*[^/{]+)?\s*\{",
    )?;
    let property_re = Regex::new(
        r"(?m)^\s*(?P<decl>(?:(?:public|private|protected|static|readonly|override)\s+)*(?P<name>[A-Za-z_$][A-Za-z0-9_$]*)\s*(?::[^;=]+)?(?:\s*=[^;]+)?;)",
    )?;

    let mut operations = Vec::new();
    let mut indexes = ImportIndexes::default();

    for file in files {
        let file_id = stable_import_uuid(&format!("file:{}", file.path));
        let mut top_level = Vec::new();
        let mut top_level_ranges = Vec::new();

        for captures in class_re.captures_iter(&file.content) {
            let whole = captures.get(0).expect("class regex has full match");
            // Scan past the heritage clause (skipping balanced `<...>`) to the real body brace,
            // so an inline object type literal like `extends Base<{ id: number }>` is not mistaken
            // for the class body.
            let Some(open_brace) = find_header_open_brace(file.content.as_bytes(), whole.end())
            else {
                bail!("class in {} has no opening brace", file.path);
            };
            let Some(close_brace) = matching_brace(file.content.as_bytes(), open_brace) else {
                bail!("class in {} has no matching closing brace", file.path);
            };
            let name = captures
                .name("name")
                .expect("class regex captures name")
                .as_str()
                .to_string();
            let class_id = stable_import_uuid(&format!("class:{}:{name}", file.path));
            let declaration = file.content[whole.start()..open_brace].trim().to_string();
            let class_body = &file.content[open_brace + 1..close_brace];
            let mut entry_operations = vec![Operation::CreateSymbol {
                symbol_id: class_id,
                parent_id: Some(file_id),
                kind: "class".to_string(),
                name: name.clone(),
                body: None,
                metadata: json!({
                    "exported": captures.name("export").is_some(),
                    "declaration": declaration
                }),
            }];
            indexes.symbols.push(ImportedSymbol {
                id: class_id,
                parent_id: Some(file_id),
                body: None,
            });
            indexes.name_index.entry(name).or_default().push(class_id);

            let children = import_class_children(
                &file.path,
                class_id,
                class_body,
                &method_re,
                &property_re,
                &mut indexes,
            )?;
            entry_operations.extend(children);
            top_level.push(ParsedTopLevel {
                start: whole.start(),
                operations: entry_operations,
            });
            top_level_ranges.push((whole.start(), close_brace + 1));
        }

        for captures in function_re.captures_iter(&file.content) {
            let whole = captures.get(0).expect("function regex has full match");
            if top_level_ranges
                .iter()
                .any(|(start, end)| whole.start() >= *start && whole.start() < *end)
            {
                continue;
            }
            let open_brace = whole.end() - 1;
            let Some(close_brace) = matching_brace(file.content.as_bytes(), open_brace) else {
                bail!("function in {} has no matching closing brace", file.path);
            };
            let name = captures
                .name("name")
                .expect("function regex captures name")
                .as_str()
                .to_string();
            let function_id = stable_import_uuid(&format!("function:{}:{name}", file.path));
            let declaration = file.content[whole.start()..open_brace].trim().to_string();
            let body = normalize_body(&file.content[open_brace + 1..close_brace]);
            top_level.push(ParsedTopLevel {
                start: whole.start(),
                operations: vec![Operation::CreateSymbol {
                    symbol_id: function_id,
                    parent_id: Some(file_id),
                    kind: "function".to_string(),
                    name: name.clone(),
                    body: Some(body.clone()),
                    metadata: json!({
                        "exported": captures.name("export").is_some(),
                        "declaration": declaration
                    }),
                }],
            });
            top_level_ranges.push((whole.start(), close_brace + 1));
            indexes.symbols.push(ImportedSymbol {
                id: function_id,
                parent_id: Some(file_id),
                body: Some(body),
            });
            indexes
                .name_index
                .entry(name)
                .or_default()
                .push(function_id);
        }

        top_level.sort_by_key(|entry| entry.start);
        top_level_ranges.sort_by_key(|range| range.0);
        let preamble = outside_ranges(&file.content, &top_level_ranges);
        operations.push(Operation::CreateSymbol {
            symbol_id: file_id,
            parent_id: None,
            kind: "file".to_string(),
            name: file
                .path
                .rsplit('/')
                .next()
                .unwrap_or(file.path.as_str())
                .to_string(),
            body: None,
            metadata: json!({
                "path": file.path,
                "preamble": preamble
            }),
        });
        for entry in top_level {
            operations.extend(entry.operations);
        }
    }

    operations.extend(import_references(&indexes)?);
    Ok(operations)
}

fn import_class_children(
    path: &str,
    class_id: Uuid,
    class_body: &str,
    method_re: &Regex,
    property_re: &Regex,
    indexes: &mut ImportIndexes,
) -> Result<Vec<Operation>> {
    let mut child_entries: Vec<(usize, usize, Operation)> = Vec::new();
    let mut method_ranges: Vec<(usize, usize)> = Vec::new();
    let bytes = class_body.as_bytes();

    for captures in method_re.captures_iter(class_body) {
        let whole = captures.get(0).expect("method regex has full match");
        // captures_iter resumes scanning *inside* the previous method's body (it only advances
        // past the opening brace), so a braced control-flow block such as `if (ready) {` would
        // otherwise be captured as a spurious method. Skip any match that starts inside a method
        // already claimed.
        if method_ranges
            .iter()
            .any(|(start, end)| whole.start() >= *start && whole.start() < *end)
        {
            continue;
        }
        let open_brace = whole.end() - 1;
        let Some(close_brace) = matching_brace(bytes, open_brace) else {
            bail!("method in {path} has no matching closing brace");
        };
        let name = captures
            .name("name")
            .expect("method regex captures name")
            .as_str()
            .to_string();
        let method_id = stable_import_uuid(&format!("method:{path}:{class_id}:{name}"));
        let signature = class_body[whole.start()..open_brace].trim().to_string();
        let body = normalize_body(&class_body[open_brace + 1..close_brace]);
        child_entries.push((
            whole.start(),
            close_brace + 1,
            Operation::CreateSymbol {
                symbol_id: method_id,
                parent_id: Some(class_id),
                kind: "method".to_string(),
                name: name.clone(),
                body: Some(body.clone()),
                metadata: json!({"signature": signature}),
            },
        ));
        method_ranges.push((whole.start(), close_brace + 1));
        indexes.symbols.push(ImportedSymbol {
            id: method_id,
            parent_id: Some(class_id),
            body: Some(body),
        });
        indexes
            .name_index
            .entry(name.clone())
            .or_default()
            .push(method_id);
        // First declaration wins so a later same-named member cannot silently shadow it.
        indexes
            .sibling_index
            .entry((class_id, name))
            .or_insert(method_id);
    }

    for captures in property_re.captures_iter(class_body) {
        let whole = captures.get(0).expect("property regex has full match");
        if method_ranges
            .iter()
            .any(|(start, end)| whole.start() >= *start && whole.start() < *end)
        {
            continue;
        }
        let name = captures
            .name("name")
            .expect("property regex captures name")
            .as_str()
            .to_string();
        let declaration = captures
            .name("decl")
            .expect("property regex captures declaration")
            .as_str()
            .trim()
            .to_string();
        let property_id = stable_import_uuid(&format!("property:{path}:{class_id}:{name}"));
        child_entries.push((
            whole.start(),
            whole.end(),
            Operation::CreateSymbol {
                symbol_id: property_id,
                parent_id: Some(class_id),
                kind: "property".to_string(),
                name: name.clone(),
                body: None,
                metadata: json!({"declaration": declaration}),
            },
        ));
        indexes.symbols.push(ImportedSymbol {
            id: property_id,
            parent_id: Some(class_id),
            body: None,
        });
        indexes
            .name_index
            .entry(name.clone())
            .or_default()
            .push(property_id);
        indexes
            .sibling_index
            .entry((class_id, name))
            .or_insert(property_id);
    }

    child_entries.sort_by_key(|entry| entry.0);
    Ok(child_entries
        .into_iter()
        .map(|(_, _, operation)| operation)
        .collect())
}

fn import_references(indexes: &ImportIndexes) -> Result<Vec<Operation>> {
    let call_re = Regex::new(r"(?P<this>this\.)?(?P<name>[A-Za-z_$][A-Za-z0-9_$]*)\s*\(")?;
    let skip = BTreeSet::from([
        "if", "for", "while", "switch", "catch", "function", "return", "throw", "new", "super",
    ]);
    let mut seen = BTreeSet::new();
    let mut operations = Vec::new();

    for symbol in &indexes.symbols {
        let Some(body) = &symbol.body else {
            continue;
        };
        for captures in call_re.captures_iter(body) {
            let name = captures
                .name("name")
                .expect("call regex captures name")
                .as_str();
            if skip.contains(name) {
                continue;
            }

            let target = if captures.name("this").is_some() {
                symbol.parent_id.and_then(|parent_id| {
                    indexes
                        .sibling_index
                        .get(&(parent_id, name.to_string()))
                        .copied()
                })
            } else {
                indexes
                    .name_index
                    .get(name)
                    .and_then(|ids| (ids.len() == 1).then_some(ids[0]))
            };

            let Some(target_id) = target else {
                continue;
            };
            if target_id == symbol.id {
                continue;
            }
            if !seen.insert((symbol.id, target_id, "calls".to_string())) {
                continue;
            }

            operations.push(Operation::CreateReference {
                reference_id: stable_import_uuid(&format!(
                    "reference:{}:{}:calls",
                    symbol.id, target_id
                )),
                from_symbol_id: symbol.id,
                to_symbol_id: target_id,
                kind: "calls".to_string(),
            });
        }
    }

    Ok(operations)
}

fn stable_import_uuid(seed: &str) -> Uuid {
    Uuid::new_v5(
        &Uuid::NAMESPACE_URL,
        format!("https://bonhomme.local/import/{seed}").as_bytes(),
    )
}

fn normalize_body(body: &str) -> String {
    body.lines()
        .map(str::trim)
        .filter(|line| !line.is_empty())
        .collect::<Vec<_>>()
        .join("\n")
}

fn outside_ranges(content: &str, ranges: &[(usize, usize)]) -> String {
    let mut out = String::new();
    let mut cursor = 0;
    for (start, end) in ranges {
        if cursor < *start {
            out.push_str(&content[cursor..*start]);
            out.push('\n');
        }
        cursor = (*end).max(cursor);
    }
    if cursor < content.len() {
        out.push_str(&content[cursor..]);
    }
    out.lines()
        .map(str::trim_end)
        .collect::<Vec<_>>()
        .join("\n")
        .trim()
        .to_string()
}

pub fn diff_slice(original: &[RenderedFile], modified: &[RenderedFile]) -> Result<Vec<Operation>> {
    let original_by_path = parse_files(original)?;
    let modified_by_path = parse_files(modified)?;
    let modified_sources = modified
        .iter()
        .map(|file| (file.path.clone(), file.clone()))
        .collect::<BTreeMap<_, _>>();
    let mut operations = Vec::new();

    for (path, modified_file) in &modified_by_path {
        let Some(original_file) = original_by_path.get(path) else {
            let source = modified_sources
                .get(path)
                .with_context(|| format!("modified source for {path} is missing"))?;
            operations.extend(import_typescript_files(std::slice::from_ref(source))?);
            continue;
        };

        // Match modified symbols back to originals (by hidden id, then by name) so a comment-less
        // edit becomes an UpdateSymbol that preserves identity. `consumed` records every original
        // that was matched, so the delete pass only removes symbols that truly disappeared and we
        // never emit a DeleteSymbol + CreateSymbol pair that would dangle an inbound reference.
        let mut consumed = BTreeSet::new();
        let mut edits = Vec::new();
        edits.extend(diff_functions(original_file, modified_file, &mut consumed)?);
        edits.extend(diff_classes(
            path,
            original_file,
            modified_file,
            &mut consumed,
        )?);

        // Deletes are emitted before edits to preserve the historical operation ordering.
        operations.extend(diff_deletes(original_file, modified_file, &consumed)?);
        operations.extend(edits);
    }

    Ok(operations)
}

fn diff_functions(
    original_file: &ParsedFile,
    modified_file: &ParsedFile,
    consumed: &mut BTreeSet<Uuid>,
) -> Result<Vec<Operation>> {
    let mut operations = Vec::new();
    let original_by_id = original_file
        .functions
        .iter()
        .filter_map(|function| function.symbol_id.map(|id| (id, function)))
        .collect::<BTreeMap<_, _>>();

    for function in &modified_file.functions {
        let matched = function
            .symbol_id
            .and_then(|id| original_by_id.get(&id).copied())
            .or_else(|| {
                original_file.functions.iter().find(|original| {
                    original.symbol_id.is_some_and(|id| !consumed.contains(&id))
                        && original.name == function.name
                })
            });

        match matched {
            Some(original_function) => {
                let symbol_id = original_function
                    .symbol_id
                    .expect("matched original carries a symbol id");
                consumed.insert(symbol_id);
                if original_function.signature != function.signature
                    || original_function.body.trim() != function.body.trim()
                    || original_function.name != function.name
                {
                    operations.push(Operation::UpdateSymbol {
                        symbol_id,
                        name: (original_function.name != function.name)
                            .then(|| function.name.clone()),
                        body: Some(function.body.clone()),
                        metadata: Some(json!({
                            "declaration": function.signature,
                            "exported": signature_is_exported(&function.signature)
                        })),
                    });
                }
            }
            None => {
                let file_symbol_id = original_file.file_symbol_id.with_context(|| {
                    format!(
                        "file {} has no bonhomme symbol metadata",
                        original_file.path
                    )
                })?;
                operations.push(Operation::CreateSymbol {
                    symbol_id: stable_import_uuid(&format!(
                        "function:{}:{}",
                        original_file.path, function.name
                    )),
                    parent_id: Some(file_symbol_id),
                    kind: "function".to_string(),
                    name: function.name.clone(),
                    body: Some(function.body.clone()),
                    metadata: json!({
                        "declaration": function.signature,
                        "exported": signature_is_exported(&function.signature)
                    }),
                });
            }
        }
    }

    Ok(operations)
}

fn diff_classes(
    path: &str,
    original_file: &ParsedFile,
    modified_file: &ParsedFile,
    consumed: &mut BTreeSet<Uuid>,
) -> Result<Vec<Operation>> {
    let mut operations = Vec::new();
    let original_methods_by_id = original_file
        .classes
        .iter()
        .flat_map(|class| &class.methods)
        .filter_map(|method| method.symbol_id.map(|id| (id, method)))
        .collect::<BTreeMap<_, _>>();

    for modified_class in &modified_file.classes {
        let original_class = original_file
            .classes
            .iter()
            .find(|class| {
                class.symbol_id == modified_class.symbol_id || class.name == modified_class.name
            })
            .with_context(|| format!("class {} is new or missing metadata", modified_class.name))?;
        let parent_id = original_class.symbol_id.with_context(|| {
            format!(
                "class {} has no bonhomme symbol metadata",
                original_class.name
            )
        })?;

        for method in &modified_class.methods {
            let matched = method
                .symbol_id
                .and_then(|id| original_methods_by_id.get(&id).copied())
                .or_else(|| {
                    original_class.methods.iter().find(|original| {
                        original.symbol_id.is_some_and(|id| !consumed.contains(&id))
                            && original.name == method.name
                    })
                });

            match matched {
                Some(original_method) => {
                    let symbol_id = original_method
                        .symbol_id
                        .expect("matched original carries a symbol id");
                    consumed.insert(symbol_id);
                    if original_method.signature != method.signature
                        || original_method.body.trim() != method.body.trim()
                        || original_method.name != method.name
                    {
                        operations.push(Operation::UpdateSymbol {
                            symbol_id,
                            name: (original_method.name != method.name)
                                .then(|| method.name.clone()),
                            body: Some(method.body.clone()),
                            metadata: Some(json!({"signature": method.signature})),
                        });
                    }
                }
                None => {
                    operations.push(Operation::CreateSymbol {
                        symbol_id: stable_import_uuid(&format!(
                            "method:{path}:{parent_id}:{}",
                            method.name
                        )),
                        parent_id: Some(parent_id),
                        kind: "method".to_string(),
                        name: method.name.clone(),
                        body: Some(method.body.clone()),
                        metadata: json!({"signature": method.signature}),
                    });
                }
            }
        }
    }

    Ok(operations)
}

fn diff_deletes(
    original_file: &ParsedFile,
    modified_file: &ParsedFile,
    consumed: &BTreeSet<Uuid>,
) -> Result<Vec<Operation>> {
    let mut operations = Vec::new();

    for original_function in &original_file.functions {
        if let Some(symbol_id) = original_function.symbol_id
            && !consumed.contains(&symbol_id)
        {
            operations.push(Operation::DeleteSymbol { symbol_id });
        }
    }

    for original_class in &original_file.classes {
        let Some(_modified_class) = modified_file.classes.iter().find(|class| {
            class.symbol_id == original_class.symbol_id || class.name == original_class.name
        }) else {
            if original_class.symbol_id.is_some() {
                bail!(
                    "class deletes are not supported by the v1 slice diff prototype: {}",
                    original_class.name
                );
            }
            continue;
        };
        for original_method in &original_class.methods {
            if let Some(symbol_id) = original_method.symbol_id
                && !consumed.contains(&symbol_id)
            {
                operations.push(Operation::DeleteSymbol { symbol_id });
            }
        }
    }

    Ok(operations)
}

/// Whether a parsed top-level function signature carries the `export` keyword, tolerating any
/// whitespace (tab/newline) between `export` and `function` so it round-trips with the importer.
fn signature_is_exported(signature: &str) -> bool {
    signature.split_whitespace().next() == Some("export")
}

pub async fn validate_typescript_files(files: &[RenderedFile]) -> Result<()> {
    let root = std::env::temp_dir().join(format!("bonhomme-tsc-{}", Uuid::new_v4()));
    let src_root = root.join("repo");
    fs::create_dir_all(&src_root).await?;

    for file in files {
        let path = src_root.join(&file.path);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).await?;
        }
        fs::write(path, &file.content).await?;
    }

    let tsconfig = json!({
        "compilerOptions": {
            "target": "ES2022",
            "module": "ESNext",
            "strict": true,
            "noEmit": true,
            "skipLibCheck": true
        },
        "include": ["repo/**/*.ts"]
    });
    fs::write(
        root.join("tsconfig.json"),
        serde_json::to_string_pretty(&tsconfig)?,
    )
    .await?;

    let mut command = if let Ok(tsc) = std::env::var("BONHOMME_TSC") {
        let mut command = Command::new(tsc);
        command
            .arg("--project")
            .arg(root.join("tsconfig.json"))
            .arg("--noEmit")
            .arg("--pretty")
            .arg("false");
        command
    } else {
        let mut command = Command::new("npx");
        command
            .arg("--yes")
            .arg("-p")
            .arg("typescript")
            .arg("tsc")
            .arg("--project")
            .arg(root.join("tsconfig.json"))
            .arg("--noEmit")
            .arg("--pretty")
            .arg("false");
        command
    };

    command.current_dir(&root);
    let output = time::timeout(std::time::Duration::from_secs(30), command.output())
        .await
        .context("typescript compiler timed out")?
        .context("failed to run TypeScript compiler")?;

    let _ = fs::remove_dir_all(&root).await;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        let stdout = String::from_utf8_lossy(&output.stdout);
        bail!("tsc rejected rendered output: {stderr}{stdout}");
    }

    Ok(())
}

fn parse_files(files: &[RenderedFile]) -> Result<BTreeMap<String, ParsedFile>> {
    let mut by_path = BTreeMap::new();
    for file in files {
        by_path.insert(file.path.clone(), parse_file(file)?);
    }
    Ok(by_path)
}

pub fn parse_file(file: &RenderedFile) -> Result<ParsedFile> {
    let file_id_re = Regex::new(r"bonhomme:file=([0-9a-fA-F-]{36})")?;
    let class_re = Regex::new(
        r"class\s+([A-Za-z_$][A-Za-z0-9_$]*)\s*(?:/\*\s*bonhomme:symbol=([0-9a-fA-F-]{36})\s*\*/)?\s*\{",
    )?;
    let method_re = Regex::new(
        r"^\s*((?:public|private|protected|async|static)\s+)*(?P<name>[A-Za-z_$][A-Za-z0-9_$]*)\s*\((?:[^()]|\([^()]*\))*\)\s*(?::\s*[^/{]+)?\s*(?:/\*\s*bonhomme:symbol=(?P<id>[0-9a-fA-F-]{36})\s*\*/)?\s*\{",
    )?;
    let function_re = Regex::new(
        r"(?m)^\s*(?P<signature>(?:export\s+)?(?:async\s+)?function\s+(?P<name>[A-Za-z_$][A-Za-z0-9_$]*)\s*\((?:[^()]|\([^()]*\))*\)\s*(?::\s*[^/{]+)?)(?:\s*/\*\s*bonhomme:symbol=(?P<id>[0-9a-fA-F-]{36})\s*\*/)?\s*\{",
    )?;

    let file_symbol_id = file_id_re
        .captures(&file.content)
        .and_then(|captures| captures.get(1))
        .and_then(|capture| Uuid::parse_str(capture.as_str()).ok());

    let mut classes = Vec::new();
    let bytes = file.content.as_bytes();
    let mut offset = 0;
    let mut class_ranges = Vec::new();

    while let Some(captures) = class_re.captures(&file.content[offset..]) {
        let whole = captures.get(0).expect("class regex has full match");
        let name = captures
            .get(1)
            .expect("class regex captures name")
            .as_str()
            .to_string();
        let symbol_id = captures
            .get(2)
            .and_then(|capture| Uuid::parse_str(capture.as_str()).ok());
        let open_brace = offset + whole.end() - 1;
        let close_brace = matching_brace(bytes, open_brace)
            .with_context(|| format!("class {name} has no matching closing brace"))?;
        let body = &file.content[open_brace + 1..close_brace];
        let methods = parse_methods(body, symbol_id, &method_re)?;
        class_ranges.push((offset + whole.start(), close_brace + 1));

        classes.push(ParsedClass {
            symbol_id,
            name,
            methods,
        });

        offset = close_brace + 1;
    }

    Ok(ParsedFile {
        path: file.path.clone(),
        file_symbol_id,
        classes,
        functions: parse_top_level_functions(&file.content, &class_ranges, &function_re)?,
    })
}

fn parse_top_level_functions(
    content: &str,
    class_ranges: &[(usize, usize)],
    function_re: &Regex,
) -> Result<Vec<ParsedFunction>> {
    let mut functions = Vec::new();
    let bytes = content.as_bytes();

    for captures in function_re.captures_iter(content) {
        let whole = captures.get(0).expect("function regex has full match");
        if class_ranges
            .iter()
            .any(|(start, end)| whole.start() >= *start && whole.start() < *end)
        {
            continue;
        }

        let open_brace = whole.end() - 1;
        let close_brace = matching_brace(bytes, open_brace)
            .with_context(|| format!("function at byte {} has no closing brace", whole.start()))?;
        let name = captures
            .name("name")
            .expect("function regex captures name")
            .as_str()
            .to_string();
        let signature = captures
            .name("signature")
            .expect("function regex captures signature")
            .as_str()
            .trim()
            .to_string();
        let symbol_id = captures
            .name("id")
            .and_then(|capture| Uuid::parse_str(capture.as_str()).ok());
        let body = content[open_brace + 1..close_brace]
            .lines()
            .map(str::trim)
            .filter(|line| !line.is_empty())
            .collect::<Vec<_>>()
            .join("\n");

        functions.push(ParsedFunction {
            symbol_id,
            name,
            signature,
            body,
        });
    }

    Ok(functions)
}

fn parse_methods(
    class_body: &str,
    parent_class_id: Option<Uuid>,
    method_re: &Regex,
) -> Result<Vec<ParsedMethod>> {
    let mut methods = Vec::new();
    let mut body_offset = 0;
    let bytes = class_body.as_bytes();

    while let Some(captures) = method_re.captures(&class_body[body_offset..]) {
        let whole = captures.get(0).expect("method regex has full match");
        let absolute_start = body_offset + whole.start();
        let absolute_end = body_offset + whole.end();
        let open_brace = absolute_end - 1;
        let close_brace = matching_brace(bytes, open_brace)
            .with_context(|| format!("method at byte {absolute_start} has no closing brace"))?;
        let signature = class_body[absolute_start..open_brace]
            .replace("/*", "")
            .replace("*/", "")
            .replace(
                captures
                    .name("id")
                    .map(|id| format!(" bonhomme:symbol={}", id.as_str()))
                    .unwrap_or_default()
                    .as_str(),
                "",
            )
            .trim()
            .to_string();
        let name = captures
            .name("name")
            .expect("method regex captures name")
            .as_str()
            .to_string();
        let symbol_id = captures
            .name("id")
            .and_then(|capture| Uuid::parse_str(capture.as_str()).ok());
        let body = class_body[open_brace + 1..close_brace]
            .lines()
            .map(str::trim)
            .filter(|line| !line.is_empty())
            .collect::<Vec<_>>()
            .join("\n");

        methods.push(ParsedMethod {
            symbol_id,
            parent_class_id,
            name,
            signature,
            body,
        });

        body_offset = close_brace + 1;
    }

    Ok(methods)
}

/// From `start`, find the index of the brace that opens a class/interface body, skipping any
/// `{` that appears inside a heritage clause's generic argument (e.g. `extends Base<{ id: number }>`)
/// and inside strings. Returns `None` if a `;` or end-of-input is reached first.
fn find_header_open_brace(bytes: &[u8], start: usize) -> Option<usize> {
    let mut angle_depth = 0_i64;
    let mut in_string: Option<u8> = None;
    let mut escaped = false;
    let mut index = start;

    while index < bytes.len() {
        let byte = bytes[index];
        if let Some(quote) = in_string {
            if escaped {
                escaped = false;
            } else if byte == b'\\' {
                escaped = true;
            } else if byte == quote {
                in_string = None;
            }
            index += 1;
            continue;
        }
        match byte {
            b'"' | b'\'' | b'`' => in_string = Some(byte),
            b'<' => angle_depth += 1,
            b'>' if angle_depth > 0 => angle_depth -= 1,
            b'{' if angle_depth == 0 => return Some(index),
            b';' if angle_depth == 0 => return None,
            _ => {}
        }
        index += 1;
    }

    None
}

/// Scan from an opening `{` to its matching `}`, correctly skipping line/block comments, string
/// literals, and template literals — including `${...}` interpolations (which may themselves
/// contain braces, strings, and further nested template literals).
fn matching_brace(bytes: &[u8], open_brace: usize) -> Option<usize> {
    // Each `Code(depth)` frame tracks brace depth for one code context (the body, or an
    // interpolation); `Template` frames are the literal text between backticks.
    enum Frame {
        Code(i64),
        Template,
    }
    let mut stack = vec![Frame::Code(0)];
    let mut in_string: Option<u8> = None;
    let mut escaped = false;
    let mut in_line_comment = false;
    let mut in_block_comment = false;
    let mut index = open_brace;

    while index < bytes.len() {
        let byte = bytes[index];
        let next = bytes.get(index + 1).copied();

        if in_line_comment {
            if byte == b'\n' {
                in_line_comment = false;
            }
            index += 1;
            continue;
        }
        if in_block_comment {
            if byte == b'*' && next == Some(b'/') {
                in_block_comment = false;
                index += 2;
            } else {
                index += 1;
            }
            continue;
        }
        if let Some(quote) = in_string {
            if escaped {
                escaped = false;
            } else if byte == b'\\' {
                escaped = true;
            } else if byte == quote {
                in_string = None;
            }
            index += 1;
            continue;
        }

        match stack.last_mut().expect("frame stack is never empty") {
            Frame::Template => {
                if escaped {
                    escaped = false;
                    index += 1;
                } else if byte == b'\\' {
                    escaped = true;
                    index += 1;
                } else if byte == b'`' {
                    stack.pop();
                    index += 1;
                } else if byte == b'$' && next == Some(b'{') {
                    stack.push(Frame::Code(1));
                    index += 2;
                } else {
                    index += 1;
                }
            }
            Frame::Code(depth) => {
                if byte == b'/' && next == Some(b'/') {
                    in_line_comment = true;
                    index += 2;
                } else if byte == b'/' && next == Some(b'*') {
                    in_block_comment = true;
                    index += 2;
                } else if matches!(byte, b'"' | b'\'') {
                    in_string = Some(byte);
                    index += 1;
                } else if byte == b'`' {
                    stack.push(Frame::Template);
                    index += 1;
                } else if byte == b'{' {
                    *depth += 1;
                    index += 1;
                } else if byte == b'}' {
                    *depth -= 1;
                    let closed = *depth == 0;
                    index += 1;
                    if closed {
                        if stack.len() == 1 {
                            return Some(index - 1);
                        }
                        // This `}` closed a `${...}` interpolation; resume the template literal.
                        stack.pop();
                    }
                } else {
                    index += 1;
                }
            }
        }
    }

    None
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core::{OperationRecord, materialize};
    use chrono::{TimeZone, Utc};

    fn record(position: i64, operation: Operation) -> OperationRecord {
        OperationRecord {
            id: Uuid::new_v4(),
            repository_id: Uuid::nil(),
            branch_id: Uuid::nil(),
            changeset_id: Uuid::nil(),
            position,
            operation,
            created_at: Utc.timestamp_opt(0, 0).unwrap(),
        }
    }

    #[test]
    fn render_is_deterministic() {
        let file = Uuid::new_v4();
        let class = Uuid::new_v4();
        let method = Uuid::new_v4();
        let records = vec![
            record(
                1,
                Operation::CreateSymbol {
                    symbol_id: file,
                    parent_id: None,
                    kind: "file".to_string(),
                    name: "OrderService.ts".to_string(),
                    body: None,
                    metadata: json!({"path": "src/OrderService.ts"}),
                },
            ),
            record(
                2,
                Operation::CreateSymbol {
                    symbol_id: class,
                    parent_id: Some(file),
                    kind: "class".to_string(),
                    name: "OrderService".to_string(),
                    body: None,
                    metadata: json!({"exported": true}),
                },
            ),
            record(
                3,
                Operation::CreateSymbol {
                    symbol_id: method,
                    parent_id: Some(class),
                    kind: "method".to_string(),
                    name: "displayName".to_string(),
                    body: Some("return \"OrderService\";".to_string()),
                    metadata: json!({"signature": "displayName(): string"}),
                },
            ),
        ];
        let graph = materialize(&records).unwrap();
        let first = render_files(&graph);
        let second = render_files(&graph);

        assert_eq!(first, second);
        assert!(first[0].content.contains("bonhomme:symbol="));
    }

    #[tokio::test]
    async fn import_typescript_files_round_trips_common_symbols() {
        let files = vec![RenderedFile {
            path: "src/OrderService.ts".to_string(),
            content: r#"
type OrderId = string;

export function formatOrder(id: OrderId): string {
  return id.toUpperCase();
}

export class OrderService {
  private prefix: string = "order";

  displayName(id: OrderId): string {
    return formatOrder(id);
  }

  summary(id: OrderId): string {
    return this.displayName(id);
  }
}
"#
            .to_string(),
        }];
        let operations = import_typescript_files(&files).unwrap();
        let records = operations
            .into_iter()
            .enumerate()
            .map(|(index, operation)| record(index as i64 + 1, operation))
            .collect::<Vec<_>>();
        let graph = materialize(&records).unwrap();
        let rendered = render_files(&graph);

        assert!(rendered[0].content.contains("type OrderId = string;"));
        assert!(rendered[0].content.contains("private prefix: string"));
        assert!(rendered[0].content.contains("formatOrder"));
        assert_eq!(graph.find_symbol("OrderService").len(), 1);
        assert_eq!(graph.find_symbol("displayName").len(), 1);
        let display_name_id = graph.find_symbol("displayName")[0].id;
        assert_eq!(graph.find_callers(display_name_id, "calls").len(), 1);
        assert_eq!(graph.find_callees(display_name_id, "calls").len(), 1);

        validate_typescript_files(&rendered).await.unwrap();
    }

    #[tokio::test]
    async fn diff_slice_imports_new_files_as_create_operations() {
        let modified = vec![RenderedFile {
            path: "src/Inventory.ts".to_string(),
            content: r#"
export function describeInventory(count: number): string {
  return `inventory:${count}`;
}
"#
            .to_string(),
        }];
        let operations = diff_slice(&[], &modified).unwrap();
        let records = operations
            .into_iter()
            .enumerate()
            .map(|(index, operation)| record(index as i64 + 1, operation))
            .collect::<Vec<_>>();
        let graph = materialize(&records).unwrap();
        let rendered = render_files(&graph);

        assert_eq!(graph.find_symbol("Inventory.ts").len(), 1);
        assert_eq!(graph.find_symbol("describeInventory").len(), 1);
        assert!(rendered[0].content.contains("describeInventory"));

        validate_typescript_files(&rendered).await.unwrap();
    }

    #[tokio::test]
    async fn diff_slice_updates_and_deletes_top_level_functions() {
        let file_id = Uuid::new_v4();
        let format_id = Uuid::new_v4();
        let unused_id = Uuid::new_v4();
        let original = vec![RenderedFile {
            path: "src/format.ts".to_string(),
            content: format!(
                r#"// bonhomme:file={file_id}

export function formatOrder(id: string): string /* bonhomme:symbol={format_id} */ {{
  return id;
}}

export function unused(): string /* bonhomme:symbol={unused_id} */ {{
  return "unused";
}}
"#
            ),
        }];
        let modified = vec![RenderedFile {
            path: "src/format.ts".to_string(),
            content: format!(
                r#"// bonhomme:file={file_id}

export function formatOrder(id: string): string /* bonhomme:symbol={format_id} */ {{
  return id.toUpperCase();
}}
"#
            ),
        }];
        let operations = diff_slice(&original, &modified).unwrap();

        assert!(matches!(
            operations[0],
            Operation::DeleteSymbol {
                symbol_id
            } if symbol_id == unused_id
        ));
        assert!(matches!(
            operations[1],
            Operation::UpdateSymbol {
                symbol_id,
                ..
            } if symbol_id == format_id
        ));

        let mut records = vec![
            record(
                1,
                Operation::CreateSymbol {
                    symbol_id: file_id,
                    parent_id: None,
                    kind: "file".to_string(),
                    name: "format.ts".to_string(),
                    body: None,
                    metadata: json!({"path": "src/format.ts"}),
                },
            ),
            record(
                2,
                Operation::CreateSymbol {
                    symbol_id: format_id,
                    parent_id: Some(file_id),
                    kind: "function".to_string(),
                    name: "formatOrder".to_string(),
                    body: Some("return id;".to_string()),
                    metadata: json!({
                        "declaration": "export function formatOrder(id: string): string",
                        "exported": true
                    }),
                },
            ),
            record(
                3,
                Operation::CreateSymbol {
                    symbol_id: unused_id,
                    parent_id: Some(file_id),
                    kind: "function".to_string(),
                    name: "unused".to_string(),
                    body: Some("return \"unused\";".to_string()),
                    metadata: json!({
                        "declaration": "export function unused(): string",
                        "exported": true
                    }),
                },
            ),
        ];
        records.extend(
            operations
                .into_iter()
                .enumerate()
                .map(|(index, operation)| record(index as i64 + 4, operation)),
        );
        let graph = materialize(&records).unwrap();
        let rendered = render_files(&graph);

        assert_eq!(graph.find_symbol("unused").len(), 0);
        assert!(rendered[0].content.contains("id.toUpperCase()"));

        validate_typescript_files(&rendered).await.unwrap();
    }

    fn import_graph(content: &str) -> SemanticGraph {
        let files = vec![RenderedFile {
            path: "src/Sample.ts".to_string(),
            content: content.to_string(),
        }];
        let operations = import_typescript_files(&files).unwrap();
        let records = operations
            .into_iter()
            .enumerate()
            .map(|(index, operation)| record(index as i64 + 1, operation))
            .collect::<Vec<_>>();
        materialize(&records).unwrap()
    }

    #[test]
    fn import_does_not_capture_control_flow_blocks_as_methods() {
        let graph = import_graph(
            r#"
export class Worker {
  run(ready: boolean): number {
    if (ready) {
      return 1;
    }
    for (let i = 0; i < 3; i = i + 1) {
      this.run(ready);
    }
    return 0;
  }
}
"#,
        );

        let methods = graph
            .symbols
            .values()
            .filter(|symbol| symbol.kind == "method")
            .collect::<Vec<_>>();
        assert_eq!(methods.len(), 1, "only the real method should be imported");
        assert_eq!(methods[0].name, "run");
        assert!(graph.find_symbol("if").is_empty());
        assert!(graph.find_symbol("for").is_empty());
    }

    #[test]
    fn import_handles_callback_typed_parameters() {
        let graph = import_graph(
            r#"
export class Events {
  on(handler: (value: number) => void): void {
    handler(value);
  }
}

export function subscribe(cb: (n: number) => void): void {
  cb(2);
}
"#,
        );

        assert_eq!(graph.find_symbol("on").len(), 1);
        assert_eq!(graph.find_symbol("subscribe").len(), 1);
    }

    #[test]
    fn import_handles_generic_object_type_in_heritage() {
        let graph = import_graph(
            r#"
export class Store extends Base<{ id: number }> {
  size(): number {
    return 0;
  }
}
"#,
        );

        assert_eq!(graph.find_symbol("Store").len(), 1);
        assert_eq!(graph.find_symbol("size").len(), 1);
        let store = graph.find_symbol("Store")[0];
        assert!(
            metadata_string(&store.metadata, "declaration")
                .unwrap()
                .contains("extends Base<{ id: number }>")
        );
    }

    #[test]
    fn matching_brace_handles_nested_template_literals() {
        let source = "{ return `a ${ok ? `X` : `Y`} b`; }";
        assert_eq!(matching_brace(source.as_bytes(), 0), Some(source.len() - 1));

        let object_in_interp = "{ return `${ {nested: 1} }`; }";
        assert_eq!(
            matching_brace(object_in_interp.as_bytes(), 0),
            Some(object_in_interp.len() - 1)
        );
    }

    #[test]
    fn diff_matches_comment_dropped_edits_by_name() {
        let file_id = Uuid::new_v4();
        let format_id = Uuid::new_v4();
        let original = vec![RenderedFile {
            path: "src/format.ts".to_string(),
            content: format!(
                r#"// bonhomme:file={file_id}

export function formatOrder(id: string): string /* bonhomme:symbol={format_id} */ {{
  return id;
}}
"#
            ),
        }];
        let modified = vec![RenderedFile {
            path: "src/format.ts".to_string(),
            content: format!(
                r#"// bonhomme:file={file_id}

export function formatOrder(id: string): string {{
  return id.trim();
}}
"#
            ),
        }];

        let operations = diff_slice(&original, &modified).unwrap();

        // A dropped symbol comment on an otherwise-unchanged-identity edit must stay an
        // UpdateSymbol that preserves the original id, never a Delete + Create.
        assert_eq!(operations.len(), 1);
        assert!(matches!(
            &operations[0],
            Operation::UpdateSymbol { symbol_id, .. } if *symbol_id == format_id
        ));
    }

    #[test]
    fn diff_added_method_id_is_deterministic() {
        let file_id = Uuid::new_v4();
        let class_id = Uuid::new_v4();
        let existing_id = Uuid::new_v4();
        let original = vec![RenderedFile {
            path: "src/Svc.ts".to_string(),
            content: format!(
                r#"// bonhomme:file={file_id}

class Svc /* bonhomme:symbol={class_id} */ {{
  existing(): void /* bonhomme:symbol={existing_id} */ {{
    return;
  }}
}}
"#
            ),
        }];
        let modified = vec![RenderedFile {
            path: "src/Svc.ts".to_string(),
            content: format!(
                r#"// bonhomme:file={file_id}

class Svc /* bonhomme:symbol={class_id} */ {{
  existing(): void /* bonhomme:symbol={existing_id} */ {{
    return;
  }}
  added(): void {{
    return;
  }}
}}
"#
            ),
        }];

        let first = diff_slice(&original, &modified).unwrap();
        let second = diff_slice(&original, &modified).unwrap();
        assert_eq!(first, second, "diff must be deterministic across runs");
        assert!(matches!(
            first.as_slice(),
            [Operation::CreateSymbol { name, .. }] if name == "added"
        ));
    }
}
